[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="uri" type="java.lang.String" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.lesson4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.lesson4.model.User" --]
